# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/temp_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from gui.assets import app_icons
from gui.views.add_dialog import AddDialog
from gui.controller.main_controller import ItemView


# class ItemType(enum):
#     """Enum to represent a MenuItem Type Enumeration"""
#     BREAKFAST = "Breakfast"
#     LUNCH = "Lunch"
#     SNACKS = "Snacks"
#     SOFT_DRINKS = "Soft Drinks"
#     BEVERAGES = "Beverages"
#     ICECREAM = "Ice Cream"


def menu_item(
        parent_widget: QtWidgets,
        item_name: str,
        item_price: int = 0,
        available: bool = True
):
    """Function to add an item to the Main Window"""

    # Initialising a menu item
    menu_item = QtWidgets.QGroupBox(parent_widget)
    menu_item.setObjectName("menu_item")
    menu_item.setMinimumSize(QtCore.QSize(111, 0))
    menu_item.setFlat(False)
    menu_item.setCheckable(True)
    menu_item.setChecked(available)

    # Initialising the layout of a menu item
    menu_item_layout = QtWidgets.QHBoxLayout(menu_item)
    menu_item_layout.setObjectName("menu_item_layout")

    # Initialising the left spacer
    left_spacer = QtWidgets.QSpacerItem(
        40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
    )
    # Add the left spacer to the menu item
    menu_item_layout.addItem(left_spacer)

    # Initialising the price label
    price_label = QtWidgets.QLabel(menu_item)
    price_label.setObjectName("price_label")
    price_label.setAlignment(
        QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter
    )
    # Add the price label to the menu item
    menu_item_layout.addWidget(price_label)

    # Initialising the price spinbox
    price = QtWidgets.QSpinBox(menu_item)
    price.setObjectName("price")
    price.setValue(item_price)
    _size = QtWidgets.QSizePolicy(
        QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
    )
    _size.setHorizontalStretch(0)
    _size.setVerticalStretch(0)
    _size.setHeightForWidth(price.sizePolicy().hasHeightForWidth())
    price.setSizePolicy(_size)
    price.setMaximum(999)
    # Add the price spinbox to the menu item layout
    menu_item_layout.addWidget(price)

    # Initialising the spacer between the price and quantity
    middle_spacer = QtWidgets.QSpacerItem(
        40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
    )
    # Add the middle spacer to the menu item layout
    menu_item_layout.addItem(middle_spacer)

    # Initialising the quantity label
    quantity_label = QtWidgets.QLabel(menu_item)
    quantity_label.setObjectName("quantity_label")
    quantity_label.setAlignment(
        QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter
    )
    # add the quantity label to the menu item layout
    menu_item_layout.addWidget(quantity_label)

    # Initialising the quantity spinbox
    quantity = QtWidgets.QSpinBox(menu_item)
    _size = QtWidgets.QSizePolicy(
        QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
    )
    _size.setHorizontalStretch(0)
    _size.setVerticalStretch(0)
    _size.setHeightForWidth(quantity.sizePolicy().hasHeightForWidth())
    quantity.setSizePolicy(_size)
    quantity.setObjectName("quantity")
    quantity.setMaximum(999)
    # Add the quantity spinbox to the menu item layout
    menu_item_layout.addWidget(quantity)

    # Initialising the right spacer to the menu item
    right_spacer = QtWidgets.QSpacerItem(
        40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
    )
    # Add the right spacer to the menu item layout
    menu_item_layout.addSpacerItem(right_spacer)

    # Re translate UI
    _translate = QtCore.QCoreApplication.translate
    menu_item.setTitle(_translate("main_window", f"{item_name}"))
    price_label.setText(_translate("main_window", "Price:"))
    price.setPrefix(_translate("main_window", "₹ "))
    quantity_label.setText(_translate("main_window", "Quantity:"))
    quantity.setSuffix(_translate("main_window", " serves"))

    return menu_item


class Ui_main_window(object):
    def setupUi(self, main_window):
        main_window.setObjectName("main_window")
        main_window.resize(437, 602)
        main_window.setMinimumSize(QtCore.QSize(359, 0))
        main_window.setStyleSheet("")
        main_window.setUnifiedTitleAndToolBarOnMac(False)
        self.central_widget = QtWidgets.QWidget(main_window)
        self.central_widget.setObjectName("central_widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.central_widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.searchbar = QtWidgets.QLineEdit(self.central_widget)
        self.searchbar.setStatusTip("")
        self.searchbar.setInputMask("")
        self.searchbar.setClearButtonEnabled(True)
        self.searchbar.setObjectName("searchbar")
        self.horizontalLayout.addWidget(self.searchbar)
        self.comboBox = QtWidgets.QComboBox(self.central_widget)
        self.comboBox.setMinimumSize(QtCore.QSize(0, 0))
        self.comboBox.setObjectName("comboBox")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Users/kevin/PycharmProjects/QuickBite/gui/assets/icons/icons/all_items.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBox.addItem(icon, "")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Users/kevin/PycharmProjects/QuickBite/gui/assets/icons/icons/filter_breakfast.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBox.addItem(icon1, "")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Users/kevin/PycharmProjects/QuickBite/gui/assets/icons/icons/filter_lunch.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBox.addItem(icon2, "")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Users/kevin/PycharmProjects/QuickBite/gui/assets/icons/icons/filter_snacks.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBox.addItem(icon3, "")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Users/kevin/PycharmProjects/QuickBite/gui/assets/icons/icons/filter_softdrinks.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBox.addItem(icon4, "")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/Users/kevin/PycharmProjects/QuickBite/gui/assets/icons/icons/filter_beverages.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBox.addItem(icon5, "")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/Users/kevin/PycharmProjects/QuickBite/gui/assets/icons/icons/filter_icecream.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.comboBox.addItem(icon6, "")
        self.horizontalLayout.addWidget(self.comboBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.scroll_area = QtWidgets.QScrollArea(self.central_widget)
        self.scroll_area.setWidgetResizable(True)
        self.scroll_area.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.scroll_area.setObjectName("scroll_area")
        self.scroll_area_widget_contents = QtWidgets.QWidget()
        self.scroll_area_widget_contents.setGeometry(QtCore.QRect(0, 0, 411, 483))
        self.scroll_area_widget_contents.setObjectName("scroll_area_widget_contents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scroll_area_widget_contents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.menu_item = QtWidgets.QGroupBox(self.scroll_area_widget_contents)
        self.menu_item.setMinimumSize(QtCore.QSize(111, 0))
        self.menu_item.setFlat(False)
        self.menu_item.setCheckable(True)
        self.menu_item.setObjectName("menu_item")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.menu_item)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.price_label = QtWidgets.QLabel(self.menu_item)
        self.price_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.price_label.setObjectName("price_label")
        self.horizontalLayout_2.addWidget(self.price_label)
        self.price = QtWidgets.QSpinBox(self.menu_item)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.price.sizePolicy().hasHeightForWidth())
        self.price.setSizePolicy(sizePolicy)
        self.price.setSuffix("")
        self.price.setMaximum(999)
        self.price.setObjectName("price")
        self.horizontalLayout_2.addWidget(self.price)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.quantity_label = QtWidgets.QLabel(self.menu_item)
        self.quantity_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.quantity_label.setObjectName("quantity_label")
        self.horizontalLayout_2.addWidget(self.quantity_label)
        self.quantity = QtWidgets.QSpinBox(self.menu_item)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.quantity.sizePolicy().hasHeightForWidth())
        self.quantity.setSizePolicy(sizePolicy)
        self.quantity.setObjectName("quantity")
        self.horizontalLayout_2.addWidget(self.quantity)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_2.addWidget(self.menu_item)
        spacerItem3 = QtWidgets.QSpacerItem(17, 302, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.scroll_area.setWidget(self.scroll_area_widget_contents)
        self.verticalLayout.addWidget(self.scroll_area)
        main_window.setCentralWidget(self.central_widget)
        self.menubar = QtWidgets.QMenuBar(main_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 437, 24))
        self.menubar.setObjectName("menubar")
        self.item = QtWidgets.QMenu(self.menubar)
        self.item.setToolTip("")
        self.item.setStatusTip("")
        self.item.setObjectName("item")
        self.app = QtWidgets.QMenu(self.menubar)
        self.app.setObjectName("app")
        self.menuFilter = QtWidgets.QMenu(self.menubar)
        self.menuFilter.setObjectName("menuFilter")
        self.sync = QtWidgets.QMenu(self.menubar)
        self.sync.setObjectName("sync")
        self.auto_sync = QtWidgets.QMenu(self.sync)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/Users/kevin/PycharmProjects/QuickBite/gui/assets/icons/icons/auto_sync.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.auto_sync.setIcon(icon7)
        self.auto_sync.setObjectName("auto_sync")
        main_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(main_window)
        self.statusbar.setObjectName("statusbar")
        main_window.setStatusBar(self.statusbar)
        self.add_action = QtWidgets.QAction(main_window)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/Users/kevin/PycharmProjects/QuickBite/gui/assets/icons/icons/add_button.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_action.setIcon(icon8)
        self.add_action.setShortcutVisibleInContextMenu(True)
        self.add_action.setObjectName("add_action")
        self.remove_action = QtWidgets.QAction(main_window)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/Users/kevin/PycharmProjects/QuickBite/gui/assets/icons/icons/remove_button.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.remove_action.setIcon(icon9)
        self.remove_action.setShortcutVisibleInContextMenu(True)
        self.remove_action.setObjectName("remove_action")
        self.info_action = QtWidgets.QAction(main_window)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/Users/kevin/PycharmProjects/QuickBite/gui/assets/icons/icons/info_action.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.info_action.setIcon(icon10)
        self.info_action.setShortcutVisibleInContextMenu(True)
        self.info_action.setObjectName("info_action")
        self.quit_action = QtWidgets.QAction(main_window)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/Users/kevin/PycharmProjects/QuickBite/gui/assets/icons/icons/quit_action.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.quit_action.setIcon(icon11)
        self.quit_action.setShortcutVisibleInContextMenu(True)
        self.quit_action.setObjectName("quit_action")
        self.filter_breakfast = QtWidgets.QAction(main_window)
        self.filter_breakfast.setCheckable(False)
        self.filter_breakfast.setIcon(icon1)
        self.filter_breakfast.setObjectName("filter_breakfast")
        self.filter_lunch = QtWidgets.QAction(main_window)
        self.filter_lunch.setCheckable(False)
        self.filter_lunch.setIcon(icon2)
        self.filter_lunch.setObjectName("filter_lunch")
        self.filter_snacks = QtWidgets.QAction(main_window)
        self.filter_snacks.setCheckable(False)
        self.filter_snacks.setIcon(icon3)
        self.filter_snacks.setObjectName("filter_snacks")
        self.filter_softdrinks = QtWidgets.QAction(main_window)
        self.filter_softdrinks.setCheckable(False)
        self.filter_softdrinks.setIcon(icon4)
        self.filter_softdrinks.setObjectName("filter_softdrinks")
        self.filter_beverages = QtWidgets.QAction(main_window)
        self.filter_beverages.setCheckable(False)
        self.filter_beverages.setIcon(icon5)
        self.filter_beverages.setObjectName("filter_beverages")
        self.refresh = QtWidgets.QAction(main_window)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/Users/kevin/PycharmProjects/QuickBite/gui/assets/icons/icons/action_refresh.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.refresh.setIcon(icon12)
        self.refresh.setObjectName("refresh")
        self.sync_15s = QtWidgets.QAction(main_window)
        self.sync_15s.setObjectName("sync_15s")
        self.sync_30s = QtWidgets.QAction(main_window)
        self.sync_30s.setObjectName("sync_30s")
        self.sync_1m = QtWidgets.QAction(main_window)
        self.sync_1m.setObjectName("sync_1m")
        self.actionEvery_5min = QtWidgets.QAction(main_window)
        self.actionEvery_5min.setObjectName("actionEvery_5min")
        self.action_2 = QtWidgets.QAction(main_window)
        self.action_2.setObjectName("action_2")
        self.action = QtWidgets.QAction(main_window)
        self.action.setObjectName("action")
        self.actionEvery_30min = QtWidgets.QAction(main_window)
        self.actionEvery_30min.setObjectName("actionEvery_30min")
        self.actionEvery_1hr = QtWidgets.QAction(main_window)
        self.actionEvery_1hr.setObjectName("actionEvery_1hr")
        self.filter_icecream = QtWidgets.QAction(main_window)
        self.filter_icecream.setCheckable(False)
        self.filter_icecream.setIcon(icon6)
        self.filter_icecream.setObjectName("filter_icecream")
        self.item.addAction(self.add_action)
        self.item.addAction(self.remove_action)
        self.app.addAction(self.info_action)
        self.app.addAction(self.quit_action)
        self.menuFilter.addAction(self.filter_breakfast)
        self.menuFilter.addAction(self.filter_lunch)
        self.menuFilter.addSeparator()
        self.menuFilter.addAction(self.filter_snacks)
        self.menuFilter.addAction(self.filter_softdrinks)
        self.menuFilter.addAction(self.filter_beverages)
        self.menuFilter.addAction(self.filter_icecream)
        self.auto_sync.addAction(self.sync_15s)
        self.auto_sync.addAction(self.sync_30s)
        self.auto_sync.addAction(self.sync_1m)
        self.sync.addAction(self.refresh)
        self.sync.addAction(self.auto_sync.menuAction())
        self.menubar.addAction(self.app.menuAction())
        self.menubar.addAction(self.item.menuAction())
        self.menubar.addAction(self.menuFilter.menuAction())
        self.menubar.addAction(self.sync.menuAction())

        # self.menu_item.deleteLater()

        self.retranslateUi(main_window)
        self.quit_action.triggered.connect(main_window.close)  # type: ignore
        self.statusbar.setStatusTip("as")
        add_dialog = QtWidgets.QDialog()
        add_item = AddDialog()
        add_item.setupUi(add_dialog)
        add_dialog.accepted.connect(lambda: print(ItemView().items[0].name.text()))
        self.add_action.triggered.connect(lambda: self.refresh_view(add_dialog))
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def refresh_view(self, dialog: QtWidgets.QDialog) -> None:
        dialog.show()
        print("ads", ItemView.items)
        for index, item in enumerate(ItemView.items):
            print("name is", item.name)
            self.verticalLayout_2.insertWidget(index + 1,
                menu_item(self.scroll_area_widget_contents, item.name, item.price)
            )


    def retranslateUi(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("main_window", "MainWindow"))
        self.searchbar.setPlaceholderText(_translate("main_window", "Search for Items..."))
        self.comboBox.setStatusTip(_translate("main_window", "Filter according to Item Type"))
        self.comboBox.setItemText(0, _translate("main_window", "All Items"))
        self.comboBox.setItemText(1, _translate("main_window", "Breakfast"))
        self.comboBox.setItemText(2, _translate("main_window", "Lunch"))
        self.comboBox.setItemText(3, _translate("main_window", "Snacks"))
        self.comboBox.setItemText(4, _translate("main_window", "Soft Drinks"))
        self.comboBox.setItemText(5, _translate("main_window", "Beverages"))
        self.comboBox.setItemText(6, _translate("main_window", "Ice Cream"))
        self.menu_item.setTitle(_translate("main_window", "Chicken Biryani"))
        self.price_label.setText(_translate("main_window", "Price:"))
        self.price.setPrefix(_translate("main_window", "₹ "))
        self.quantity_label.setText(_translate("main_window", "Quantity:"))
        self.quantity.setSuffix(_translate("main_window", " serves"))
        self.item.setTitle(_translate("main_window", "Item"))
        self.app.setTitle(_translate("main_window", "App"))
        self.menuFilter.setTitle(_translate("main_window", "Filter"))
        self.sync.setTitle(_translate("main_window", "Refresh"))
        self.auto_sync.setTitle(_translate("main_window", "Auto Sync"))
        self.add_action.setText(_translate("main_window", "Add"))
        self.add_action.setStatusTip(_translate("main_window", "Add an item to the menu"))
        self.add_action.setShortcut(_translate("main_window", "Ctrl+N"))
        self.remove_action.setText(_translate("main_window", "Remove"))
        self.remove_action.setStatusTip(_translate("main_window", "Click to remove a menu item"))
        self.remove_action.setShortcut(_translate("main_window", "Ctrl+D"))
        self.info_action.setText(_translate("main_window", "About"))
        self.info_action.setStatusTip(_translate("main_window", "Click to learn more about the app"))
        self.info_action.setShortcut(_translate("main_window", "Ctrl+I"))
        self.quit_action.setText(_translate("main_window", "Quit"))
        self.quit_action.setStatusTip(_translate("main_window", "Click to quit the app"))
        self.quit_action.setShortcut(_translate("main_window", "Ctrl+Q"))
        self.filter_breakfast.setText(_translate("main_window", "Breakfast"))
        self.filter_lunch.setText(_translate("main_window", "Lunch"))
        self.filter_snacks.setText(_translate("main_window", "Snacks"))
        self.filter_softdrinks.setText(_translate("main_window", "Soft Drinks"))
        self.filter_beverages.setText(_translate("main_window", "Beverages"))
        self.refresh.setText(_translate("main_window", "Refresh"))
        self.refresh.setShortcut(_translate("main_window", "Ctrl+R"))
        self.sync_15s.setText(_translate("main_window", "Every 15s"))
        self.sync_30s.setText(_translate("main_window", "Every 30s"))
        self.sync_1m.setText(_translate("main_window", "Every 1min"))
        self.actionEvery_5min.setText(_translate("main_window", "Every 5min"))
        self.action_2.setText(_translate("main_window", "Every 10min"))
        self.action.setText(_translate("main_window", "Every 15min"))
        self.actionEvery_30min.setText(_translate("main_window", "Every 30min"))
        self.actionEvery_1hr.setText(_translate("main_window", "Every 1hr"))
        self.filter_icecream.setText(_translate("main_window", "Ice Cream"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    main_window = QtWidgets.QMainWindow()
    ui = Ui_main_window()
    ui.setupUi(main_window)
    main_window.show()
    sys.exit(app.exec_())
